config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  use_doorkeeper
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "questions#index"
  get 'search', to: 'search#index'

  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  namespace :api do
    namespace :v1 do
      use_doorkeeper

      resources :profiles, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, shallow: true, except: [:new, :edit] do
        resources :answers, shallow: true, only: [:index, :create, :update, :destroy] do
          resources :comments, shallow: true, only: [:index]
        end
        resources :comments, shallow: true, only: [:index]
      end
    end
  end

  resources :questions do
    member do
      patch :mark_best_answer
      patch :unmark_best_answer
    end

    resources :answers, shallow: true, except: [ :index, :show ] do
      resources :comments, shallow: true, only: [ :new, :create ]
      resource :subscriptions, only: [:create, :destroy], shallow: true

    end
    resource :subscriptions, only: [:create, :destroy], shallow: true

    resources :comments, shallow: true, only: [ :new, :create ]
  end
  resources :attachments, only: [ :destroy ]
  resources :links, only: [ :destroy ]
  resources :rewards, only: :index
  resources :votes, only: [ :create ] do
    collection do
      delete :destroy, to: 'votes#destroy', as: 'delete_vote'
    end
  end
  resources :live_feed, only: [ :index ]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include FileAttachable
  include Authorable
  include Votable
  include Subscribable


  before_destroy :reset_best_answer

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :answers, dependent: :destroy
  has_one :reward, dependent: :destroy
  belongs_to :best_answer, class_name: 'Answer', optional: true

  accepts_nested_attributes_for :links, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :reward, allow_destroy: true, reject_if: :all_blank
  searchkick


  validates :title, :body, presence: true

  after_create_commit do
    broadcast_prepend_later_to "questions", target: "questions", partial: "live_feed/question", locals: { question: self }
  end

  after_update_commit do
    broadcast_replace_later_to "questions", target: "question_#{id}", partial: "live_feed/question", locals: { question: self }
  end

  after_destroy_commit do
    broadcast_remove_to "questions", target: "question_#{id}"
  end

  private

  def reset_best_answer
    self.best_answer = nil
  end

end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < BaseController
      before_action :set_question, only: [:show, :update, :destroy]

      def index
        questions = policy_scope(Question)
        render json: questions, each_serializer: QuestionSerializer
      end

      def show
        authorize @question
        render json: @question, serializer: QuestionSerializer
      end

      def create
        question = current_user.questions.new(question_params)
        authorize question
        if question.save
          render json: question, serializer: QuestionSerializer, status: :created
        else
          render json: { errors: question.errors }, status: :unprocessable_entity
        end
      end

      def update
        authorize @question
        if @question.update(question_params)
          render json: @question, serializer: QuestionSerializer
        else
          render json: { errors: @question.errors }, status: :unprocessable_entity
        end
      end

      def destroy
        authorize @question
        @question.destroy
        head :no_content
      end

      private

      def set_question
        @question = Question.find(params[:id])
      end

      def question_params
        params.require(:question).permit(:title, :body)
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_question, only: [ :show, :edit, :update, :destroy, :mark_best_answer, :unmark_best_answer ]

  def index
    @questions = policy_scope(Question)
    render template: 'questions/index', locals: { questions: @questions }

  end

  def show
    @best_answer = @question.best_answer
    @answers = @question.answers.where.not(id: @question.best_answer_id).order(updated_at: :desc)
    @links = @question.links

    @answer = @question.answers.build
    @answer.links.build
  end

  def new
    @question = Question.new
    @question.links.build
    @question.build_reward
    authorize @question
  end

  def edit
    authorize @question
    @question.links.build if @question.links.blank?
    @question.build_reward if @question.reward.blank?
  end

  def create
    @question = current_user.questions.build(question_params)
    authorize @question

    if @question.save
      questions = Question.all

      respond_to do |format|
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.turbo_stream { render 'questions/create', locals: { questions: questions } }
      end
    else
      @question.links.build if @question.links.blank?
      @question.build_reward if @question.reward.blank?
      respond_to do |format|
        format.html do
          flash[:alert] = @question.errors.full_messages.join(", ")
          render :new, status: :unprocessable_entity
        end
        format.turbo_stream do
          render 'questions/create_error', locals: { question: @question, message: @question.errors.full_messages.join(", ") }, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    # return handle_unauthorized_update unless current_user.author_of?(@question)
    authorize @question

    @question.update(question_params) ? handle_successful_update : handle_failed_update
  end

  def destroy
    # return handle_unauthorized_destroy unless current_user.author_of?(@question)
    authorize @question

    @question.destroy
    handle_successful_destroy
  end

  def mark_best_answer
    @answer = @question.answers.find(params[:answer_id])
    authorize @question, :mark_best_answer?

    if @question.update(best_answer: @answer)
      @question.reward.update(user: @answer.author) if @question.reward
      @best_answer = @question.best_answer
      @answers = @question.answers.where.not(id: @question.best_answer_id).order(updated_at: :desc)
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("answers", partial: 'answers/answers_list') }
        format.html { redirect_to @question, notice: 'Best answer selected.' }
      end

    else
      respond_to do |format|
        # format.turbo_stream { render turbo_stream: turbo_stream.replace('best_answer', partial: 'questions/best_answer', locals: { question: @question }), status: :unprocessable_entity } # Just for future
        format.html { redirect_to @question, alert: 'Failed to select the best answer.', status: :unprocessable_entity }
      end
    end
    # else
    #   redirect_to @question, alert: 'You are not authorized to select the best answer.', status: :forbidden
    # end
  end

  def unmark_best_answer
    authorize @question, :unmark_best_answer?
    if @question.update(best_answer: nil)
      @question.reward.update(user: nil) if @question.reward
      @answers = @question.answers.order(updated_at: :desc)
      respond_to do |format|
        format.html { redirect_to @question }
        format.turbo_stream { render turbo_stream: turbo_stream.update("answers", partial: 'answers/answers_list') }
      end
    else
      redirect_to @question, alert: 'Failed to unmark the best answer.', status: :unprocessable_entity
    end
    # else
    #   redirect_to @question, alert: 'You are not authorized to unmark the best answer.', status: :forbidden
    # end
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :best_answer_id, files: [], links_attributes: [:id, :name, :url, :_destroy], reward_attributes: [:title, :image])
  end

  def handle_unauthorized_update
    respond_to do |format|
      format.html { redirect_to @question, alert: 'Only the author can edit this question.', status: :forbidden }
      format.turbo_stream { render turbo_stream: helpers.render_flash_alert('Only the author can edit this question.'), status: :forbidden }
    end
  end

  def handle_unauthorized_destroy
    respond_to do |format|
      format.html { redirect_to questions_path, alert: 'You can delete only your own questions.', status: :forbidden }
      format.turbo_stream { render turbo_stream: helpers.render_flash_alert('You can delete only your own questions.'), status: :forbidden }
    end
  end

  def handle_successful_update
    message = 'Question successfully updated.'
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Question successfully updated.' }
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(helpers.dom_id(@question), partial: 'questions/question', locals: { question: @question }),
          helpers.render_flash_notice('Question successfully updated.')
        ]
      end

    end
  end

  def handle_failed_update
    respond_to do |format|
      format.html { render :edit }
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('question_form', partial: 'questions/form')
        ], status: :unprocessable_entity
      end
    end
  end

  def handle_successful_destroy
    respond_to do |format|
      if turbo_frame_request?
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.remove(@question),
            helpers.render_flash_notice('Your question was successfully deleted.')
          ]
        end
      else
        format.html { redirect_to questions_path, notice: "Your question was successfully deleted." }
      end
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question, data: { turbo_frame: dom_id(@question), controller: 'links' }, id: 'question_form' do |f|
  - if @question.errors.any?
    .notification.is-danger.error-message
      p There were errors with your submission:
      ul
        - @question.errors.full_messages.each do |message|
          li= message
  div
    = f.label :title
    = f.text_field :title

  div
    = f.label :body
    = f.text_area :body

  div
    = f.fields_for :reward do |reward_fields|
      = reward_fields.label :title, "Название награды"
      = reward_fields.text_field :title

      = reward_fields.label :image, "Изображение награды"
      = reward_fields.file_field :image

  div

    = f.label :files
    = f.file_field :files, multiple: true

  - if @question.files.attached?
    ul
      - @question.files.each do |file|
        li id="file_#{file.id}"
          = f.hidden_field :files, multiple: true, value: file.signed_id

          = link_to file.filename.to_s, url_for(file)
          = link_to 'Remove', attachment_path(file),
                  data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this file?' },
                  class: 'delete-file-link',
                  style: 'color: red; margin-left: 10px;'

  div
    p Links

    .links data-links-target="links"
      = f.fields_for :links do |l|
        = render 'link_fields', f: l

    = link_to 'Add Link', '#', data: { action: 'links#addLink' }

  div
    = f.submit 'Save'

  // Template for new added links
  = content_tag :template, '', id: 'link_template', data: { links_target: 'template' } do
    = f.fields_for :links, Link.new, child_index: 'NEW_RECORD' do |l|
      .nested-fields
        = render 'link_fields', f: l

app/views/questions/_link_fields.html.slim
.nested-fields id="link_#{f.object.id || 'NEW_RECORD'}" data-controller="remove-link"
  = f.hidden_field :id
  p
    = f.label :name, 'Link name'
    = f.text_field :name

  p
    = f.label :url
    = f.text_field :url
    = f.hidden_field :_destroy, value: "false", data: { 'remove-link-target': 'destroyField' }

  = link_to 'Remove', '#', data: { action: 'remove-link#remove'}

app/views/questions/_question.html.slim
= turbo_frame_tag dom_id(question) do
  li.question
    header.card-header
      .card-header-title = link_to question.title, question_path(question), data: { turbo: false }
      p.subtitle Asked by: #{question.author.email}
    .card-content
      .media
        .media-left
          figure.image.is-48x48
            - if question.reward
              = image_tag question.reward.image.variant(resize_to_limit: [ 150, 150 ])
        .media-content
          p.content.mb-4 = truncate(question.body, length: 100)
          - if user_signed_in? && !current_user.author_of?(question)
            .nav.level.is-mobile.vote-area id=dom_id(question) data-controller="vote" data-vote-votable-id="#{question.id}" data-vote-votable-type="Question"
              p#error-message.is-hidden  data-vote-target="errorMessage"
              .level-right
                p.level-item Rating:
                span.level-item.vote__rating data-vote-target="rating"= question.rating
                a.level-item
                  span.vote__up data-action="click->vote#upvote"
                    = image_tag 'thumbs-up.svg', class: 'icon is-small icon-success'
                a.level-item
                  span.vote__down data-action="click->vote#downvote"
                    = image_tag 'thumbs-down.svg', class: 'icon is-small'
                a.level-item
                  span.vote__cancel data-action="click->vote#cancelVote"
                    = image_tag 'trash-can.svg', class: 'icon is-small'
    - if question.links.any? || question.files.attached?
      .title.has-text-centered Attachments
      .columns
        - if question.links.any?
          .column.is-half
            .title.has-text-centered Links:
            .section#question-links
              ul
                - question.links.each do |link|
                  li = render partial: 'shared/link', locals: { link: link }
        .column.is-half
          .title.has-text-centered Files:
          - if question.files.attached?
            ul.attachments
              - question.files.each do |file|
                li id="file_#{file.id}"
                  = link_to file.filename.to_s, url_for(file)
                  - if user_signed_in? && current_user.author_of?(question)
                    = link_to 'X', attachment_path(file),
                            data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this file?' },
                            class: 'delete-file-link',
                            style: 'color: red; margin-left: 10px;'

    = render partial: 'comments/comments', locals: { commentable: question }
    = render partial: 'subscriptions/subscription_button', locals: { subscribable: question }
    - if user_signed_in? && current_user.author_of?(question)
      .card-footer
        .card-footer-item
          = link_to 'Edit Question', edit_question_path(question), data: { turbo_frame: dom_id(question) }
        .card-footer-item
          = link_to 'Delete Question', question_path(question),
                  data: { turbo_method: :delete,
                          turbo_frame: '_top',
                          turbo_confirm: 'Are you sure?',
                          turbo_action: 'advance',
                          }

app/views/questions/create.turbo_stream.slim
/# locals: (questions:)
= turbo_stream.replace 'main' do
  = render template: 'questions/index', locals: { questions: questions }
= render_flash_notice('Question was successfully created.')

app/views/questions/create_error.turbo_stream.slim
/# locals: (question:, message: )
= turbo_stream.replace 'main' do
  = render template: 'questions/new', locals: { question: question }
/ = render_flash_notice(message)

app/views/questions/edit.html.slim
= turbo_frame_tag dom_id(@question) do
  = render 'form', question: @question

app/views/questions/index.html.slim
/# locals: (questions:)
= turbo_frame_tag 'main' do
  = link_to 'Live Feed', live_feed_index_path
  .p
    = link_to 'Search', search_path, target: "_top"

  .hero.is-info
    .title.has-text-centered List of Questions
  = link_to 'Ask question', new_question_path

  ul
    - questions.each do |question|
      = render partial: 'questions/question', locals: { question: question }

app/views/questions/mark_best_answer.turbo_stream.erb
<% if @previous_best_answer %>
  <%= turbo_stream.replace dom_id(@previous_best_answer) do %>
    <%= render @previous_best_answer %>
  <% end %>
<% end %>

<%= turbo_stream.replace dom_id(@answer) do %>
  <%= render @answer %>
<% end %>

<%= turbo_stream.replace 'reloadTrigger' do %>
  <div>Updated content at <%= Time.current.to_i %></div>
<% end %>

app/views/questions/new.html.slim
= turbo_frame_tag 'main' do
  = render 'shared/errors', resource: @question
  = render 'form', question: @question

app/views/questions/show.html.slim
= turbo_frame_tag 'main' do
  .outer-container
    = link_to 'Index', questions_path
    = link_to 'Live Feed', live_feed_index_path
    section.show data-controller="reload-on-best-answer" data-reload-on-best-answer-target="bestAnswer"
      = render partial: 'questions/question', locals: { question: @question }
      h2 Answers
      = turbo_frame_tag "answers" do
        = render 'answers/answers_list'

      - if user_signed_in? && policy(Answer).create?
        h3 Write your answer

        #answer_form
          = render 'answers/form', question: @question, answer: @answer || Answer.new
      - else
        p You need to sign in or sign up before creating answers.