config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  use_doorkeeper
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "questions#index"
  get 'search', to: 'search#index'

  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  namespace :api do
    namespace :v1 do
      use_doorkeeper

      resources :profiles, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, shallow: true, except: [:new, :edit] do
        resources :answers, shallow: true, only: [:index, :create, :update, :destroy] do
          resources :comments, shallow: true, only: [:index]
        end
        resources :comments, shallow: true, only: [:index]
      end
    end
  end

  resources :questions do
    member do
      patch :mark_best_answer
      patch :unmark_best_answer
    end

    resources :answers, shallow: true, except: [ :index, :show ] do
      resources :comments, shallow: true, only: [ :new, :create ]
      resource :subscriptions, only: [:create, :destroy], shallow: true

    end
    resource :subscriptions, only: [:create, :destroy], shallow: true

    resources :comments, shallow: true, only: [ :new, :create ]
  end
  resources :attachments, only: [ :destroy ]
  resources :links, only: [ :destroy ]
  resources :rewards, only: :index
  resources :votes, only: [ :create ] do
    collection do
      delete :destroy, to: 'votes#destroy', as: 'delete_vote'
    end
  end
  resources :live_feed, only: [ :index ]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/views/shared/_errors.html.slim
- object = local_assigns[:object] || resource
- if object&.errors.present?
  .answer-errors
    ul
      - object.errors.full_messages.each do |message|
        li = message
- elsif flash.any?
  - flash.each do |key, message|
    .flash(class="#{key}")
      = message

app/views/shared/_flash.html.slim
= turbo_frame_tag 'flash-messages' do
  - flash.each do |key, message|
    div class="#{key}"
      = message

app/views/shared/_flash_alert.turbo_stream.slim
/# locals: (message:)

= render_flash_alert(message)

app/views/shared/_flash_notice.turbo_stream.slim
/# locals: (message:)

= render_flash_notice(message)

app/views/shared/_link.html.slim
- if link.gist?
  .gist-preview id=dom_id(link)
    = link_to link.name.to_s, link.url, target: '_blank'
    div data-controller="gist-preview" data-url=link.url
      div data-gist-preview-target="output"
        | Loading Gist preview...
    - if user_signed_in? && current_user.author_of?(link.linkable)
      = link_to 'X', link_path(link),
              data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this link?' },
              class: 'delete-link', style: 'color: red; margin-left: 10px;'

- else
  li.microlink_card id=dom_id(link)
    div data-controller="link-preview" data-url=link.url
      div data-link-preview-target="linkPreview"
        | Loading link preview...
    - if user_signed_in? && current_user.author_of?(link.linkable)
      = link_to 'X', link_path(link),
              data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this link?' },
              class: 'delete-link', style: 'color: red; margin-left: 10px;'

app/views/shared/_link_template.html.slim
= content_tag :template, '', id: 'link_template', data: { links_target: 'template' } do
  = f.fields_for :links, Link.new, child_index: 'NEW_RECORD' do |l|
    .nested-fields
      = render 'link_fields', f: l