config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  use_doorkeeper
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "questions#index"
  get 'search', to: 'search#index'

  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  namespace :api do
    namespace :v1 do
      use_doorkeeper

      resources :profiles, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, shallow: true, except: [:new, :edit] do
        resources :answers, shallow: true, only: [:index, :create, :update, :destroy] do
          resources :comments, shallow: true, only: [:index]
        end
        resources :comments, shallow: true, only: [:index]
      end
    end
  end

  resources :questions do
    member do
      patch :mark_best_answer
      patch :unmark_best_answer
    end

    resources :answers, shallow: true, except: [ :index, :show ] do
      resources :comments, shallow: true, only: [ :new, :create ]
      resource :subscriptions, only: [:create, :destroy], shallow: true

    end
    resource :subscriptions, only: [:create, :destroy], shallow: true

    resources :comments, shallow: true, only: [ :new, :create ]
  end
  resources :attachments, only: [ :destroy ]
  resources :links, only: [ :destroy ]
  resources :rewards, only: :index
  resources :votes, only: [ :create ] do
    collection do
      delete :destroy, to: 'votes#destroy', as: 'delete_vote'
    end
  end
  resources :live_feed, only: [ :index ]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include FileAttachable
  include Authorable
  include Votable
  include ActionView::RecordIdentifier
  include Subscribable
  searchkick


  has_many :comments, as: :commentable, dependent: :destroy

  belongs_to :question

  accepts_nested_attributes_for :links, allow_destroy: true, reject_if: :all_blank

  validates :body, presence: true
  after_create_commit :broadcast_answer
  after_create_commit :notify_subscribers


  after_update_commit do
    broadcast_update_to "questions",
                        target: "#{dom_id(self)}",
                        partial: "live_feed/answer",
                        locals: { answer: self }
  end

  after_destroy_commit do
    broadcast_remove_to "questions", target: "answer_#{id}"
  end

  private

  def broadcast_answer
    broadcast_prepend_to "questions", target: "question_#{question.id}_answers", partial: "live_feed/answer", locals: { answer: self }
  end

  def notify_subscribers
    NotificationService.call(self)
  end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [ :new, :create ]
  before_action :set_answer, only: [ :edit, :update, :destroy ]

  def new
    @answer = @question.answers.build
    @answer.author = current_user
    @answer.links.build
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.author = current_user
    authorize @answer

    respond_to do |format|
      if @answer.save
        @new_answer = @question.answers.build
        @new_answer.links.build
        format.html { redirect_to @question, notice: "Answer was successfully created." }
        format.turbo_stream { render 'answers/create', locals: { answer: @new_answer } }
      else
        @answers = @question.answers
        @answer.links.build if @answer.links.blank?
        format.html do
          render "questions/show", status: :unprocessable_entity
        end
        format.turbo_stream { render 'answers/create_error', status: :unprocessable_entity }
      end
    end
  end

  def edit
    @question = @answer.question

    authorize @answer

    @answer.links.build if @answer.links.blank?
  end

  def update
    @question = @answer.question
    authorize @answer

    if @answer.update(answer_params)
      respond_to do |format|
        format.html { redirect_to @answer.question, notice: 'Your answer was successfully updated.' }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(helpers.dom_id(@answer), partial: 'answers/answer', locals: { answer: @answer }),
            helpers.render_flash_notice('Your answer was successfully updated.')
          ]
        end
      end
    else
      handle_failed_update
    end
  end

  def destroy
    @question = @answer.question
    respond_to do |format|
      authorize @answer

      @answer.destroy
      format.html { redirect_to @question, notice: "Your answer was successfully deleted." }
      format.turbo_stream do
        if turbo_frame_request?
          render turbo_stream: [
            turbo_stream.remove(@answer),
            helpers.render_flash_notice("Your answer was successfully deleted.")
          ]
        end
      end
    end
  end

  private

  def handle_unauthorized_update
    respond_to do |format|
      format.html { redirect_to @question, alert: 'You can update only your own answers.', status: :forbidden }
      format.turbo_stream { render turbo_stream: helpers.render_flash_alert('You can update only your own answers.'), status: :forbidden }
    end
  end

  def handle_failed_update

    respond_to do |format|
      format.html { render :edit, alert: 'Failed to update the answer. Please fix the errors.', status: :unprocessable_entity }
      format.turbo_stream { render turbo_stream: [
        turbo_stream.update(dom_id(@answer), partial: 'answers/form', locals: { answer: @answer }),
      ], status: :unprocessable_entity }
    end
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [ :id, :name, :url, :_destroy ])
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < BaseController
      before_action :set_answer, only: [:show, :update, :destroy]
      before_action :set_question, only: [:create]

      def index
        answers = policy_scope(Answer).where(question_id: params[:question_id])
        render json: answers, each_serializer: AnswerSerializer
      end

      def show
        authorize @answer
        render json: @answer, serializer: AnswerSerializer
      end

      def create
        answer = @question.answers.new(answer_params.merge(author: current_user))
        authorize answer
        if answer.save
          render json: answer, serializer: AnswerSerializer, status: :created
        else
          render json: { errors: answer.errors }, status: :unprocessable_entity
        end
      end

      def update
        authorize @answer
        if @answer.update(answer_params)
          render json: @answer, serializer: AnswerSerializer
        else
          render json: { errors: @answer.errors }, status: :unprocessable_entity
        end
      end

      def destroy
        authorize @answer
        @answer.destroy
        head :no_content
      end

      private

      def set_answer
        @answer = Answer.find(params[:id])
      end

      def set_question
        @question = Question.find(params[:question_id])
      end

      def answer_params
        params.require(:answer).permit(:body)
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
= turbo_frame_tag dom_id(answer) do
  - if answer.body.present?
    li.answer id="answer-#{answer.id}" class=(answer == @question.best_answer ? 'best-answer' : 'answer')
      header.card-header
        p.subtitle Answered by: #{answer.author.email}
      .card-content
        div
          p.content.mb-4 = answer.body
          - if user_signed_in? && !current_user.author_of?(answer)
            .nav.level.is-mobile.vote-area id=dom_id(answer) data-controller="vote" data-vote-votable-id="#{answer.id}" data-vote-votable-type="Answer"
              p#error-message.is-hidden data-vote-target="errorMessage"
              .level-right
                p.level-item Rating:
                span.level-item.vote__rating data-vote-target="rating"= answer.rating
                a.level-item
                  span.vote__up data-action="click->vote#upvote"
                    = image_tag 'thumbs-up.svg', class: 'icon is-small icon-success'
                a.level-item
                  span.vote__down data-action="click->vote#downvote"
                    = image_tag 'thumbs-down.svg', class: 'icon is-small'
                a.level-item
                  span.vote__cancel data-action="click->vote#cancelVote"
                    = image_tag 'trash-can.svg', class: 'icon is-small'
          .title.has-text-centered Attachments
          .columns
            .column.is-half
              .title.has-text-centered Links:
              .section#answer-links
                ul
                  - answer.links.each do |link|
                    li = render partial: 'shared/link', locals: { link: link }
            .column.is-half
              .title.has-text-centered Files:
              - if answer.files.attached?
                ul.attachments
                  - answer.files.each do |file|
                    li id="file_#{file.id}"
                      = link_to file.filename.to_s, url_for(file)
                      - if user_signed_in? && current_user.author_of?(answer)
                        = link_to 'X', attachment_path(file),
                                data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this file?' },
                                class: 'delete-file-link',
                                style: 'color: red; margin-left: 10px;'
          - if user_signed_in? && current_user.author_of?(answer.question) && answer.persisted?
            - if answer == @question.best_answer
              = button_to 'Unmark Best', unmark_best_answer_question_path(@question, answer_id: answer.id), data: { turbo_method: :patch }, method: :patch, class: 'button is-dark'
            - else
              = button_to 'Mark as Best', mark_best_answer_question_path(@question, answer_id: answer.id), method: :patch, data: { turbo_method: :patch }, class: 'button is-warning'
        = render partial: 'comments/comments', locals: { commentable: answer }
        = render partial: 'subscriptions/subscription_button', locals: { subscribable: answer }

        - if user_signed_in? && current_user.author_of?(answer) && answer.persisted?
          .card-footer
            .card-footer-item
              = link_to 'Edit', edit_answer_path(answer), data: { turbo_frame: dom_id(answer) }
            .card-footer-item
              = link_to 'Delete Answer', answer_path(answer), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

app/views/answers/_answers_list.html.slim
ul#answers
  - if @best_answer
    = render 'answers/best_answer', answer: @best_answer
  - if @answers.present?
    = render partial: 'answers/answer', collection: @answers, as: :answer
  - else
    p No answers available.

app/views/answers/_best_answer.html.slim
= turbo_frame_tag dom_id(answer) do
  - if answer.body.present?
    li.answer id="answer-#{answer.id}" class=(answer == @question.best_answer ? 'best-answer' : 'answer')
      header.card-header
        div.is-flex.is-justify-content-space-between.is-align-items-center
          - if answer == @question.best_answer
            .card-header-title.has-text-warning.has-text-weight-bold.has-text-size-1 Best answer
          p.subtitle.has-text-right Answered by: #{answer.author.email}

      .card-content
        div
          p.content.mb-4 = answer.body
          - if user_signed_in? && !current_user.author_of?(answer)
            .nav.level.is-mobile.vote-area id=dom_id(answer) data-controller="vote" data-vote-votable-id="#{answer.id}" data-vote-votable-type="Answer"
              p#error-message.is-hidden data-vote-target="errorMessage"
              .level-right
                p.level-item Rating:
                span.level-item.vote__rating data-vote-target="rating"= answer.rating
                a.level-item
                  span.vote__up data-action="click->vote#upvote"
                    = image_tag 'thumbs-up.svg', class: 'icon is-small icon-success'
                a.level-item
                  span.vote__down data-action="click->vote#downvote"
                    = image_tag 'thumbs-down.svg', class: 'icon is-small'
                a.level-item
                  span.vote__cancel data-action="click->vote#cancelVote"
                    = image_tag 'trash-can.svg', class: 'icon is-small'
          .title.has-text-centered Attachments
          .columns
            .column.is-half
              .title.has-text-centered Links:
              .section#answer-links
                ul
                  - answer.links.each do |link|
                    li = render partial: 'shared/link', locals: { link: link }
            .column.is-half
              .title.has-text-centered Files:
              - if answer.files.attached?
                ul.attachments
                  - answer.files.each do |file|
                    li id="file_#{file.id}"
                      = link_to file.filename.to_s, url_for(file)
                      - if user_signed_in? && current_user.author_of?(answer)
                        = link_to 'X', attachment_path(file),
                                data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this file?' },
                                class: 'delete-file-link',
                                style: 'color: red; margin-left: 10px;'
          - if user_signed_in? && current_user.author_of?(answer.question) && answer.persisted?
            - if answer == @question.best_answer

              = button_to 'Unmark Best', unmark_best_answer_question_path(@question, answer_id: answer.id), data: { turbo_method: :patch }, method: :patch, class: 'button is-dark'
            - else
              = button_to 'Mark as Best', mark_best_answer_question_path(@question, answer_id: answer.id), data: { turbo_method: :patch }, method: :patch, class: 'button is-warning'
        = render partial: 'comments/comments', locals: { commentable: answer }

        - if user_signed_in? && current_user.author_of?(answer) && answer.persisted?
          .card-footer
            .card-footer-item
              = link_to 'Edit', edit_answer_path(answer), data: { turbo_frame: dom_id(answer) }
            .card-footer-item
              = link_to 'Delete Answer', answer_path(answer), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

app/views/answers/_form.html.slim
= form_with model: [question, answer], url: question_answers_path(@question), id: 'answer_form', remote: true, data: { controller: 'links' } do |f|

  - if answer.errors.any?
    .notification.is-danger.error-message
      p There were errors with your submission:
      ul
        - answer.errors.full_messages.each do |message|
          li= message
  = render 'answers/form_fields', f: f, answer: answer

  div
    = f.submit 'Submit Answer'

  // Reuse the link template partial
  = render 'shared/link_template', f: f

app/views/answers/_form_edit.html.slim
= form_with model: answer, url: answer_path(answer), method: :patch, id: 'answer_form', remote: true, data: { controller: 'links' } do |f|
  = render 'answers/form_fields', f: f, answer: answer

  div
    = f.submit 'Update Answer'

  // Reuse the link template partial
  = render 'shared/link_template', f: f

app/views/answers/_form_fields.html.slim
= render 'shared/errors', object: answer

div
  = f.label :body, 'Your Answer'
  = f.text_area :body, id: 'answer_body', rows: 3, placeholder: "Type your answer here..."

p
  = f.label :files
  = f.file_field :files, multiple: true
  - if answer.files.attached?
    ul
      - answer.files.each do |file|
        li id="file_#{file.id}"
          = f.hidden_field :files, multiple: true, value: file.signed_id
          = link_to file.filename.to_s, url_for(file)
          = link_to 'Remove', attachment_path(file),
                  data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this file?' },
                  class: 'delete-file-link',
                  style: 'color: red; margin-left: 10px;'

div
  p Links
  .links data-links-target="links"
    = f.fields_for :links do |l|
      = render 'link_fields', f: l

  = link_to 'Add Link', '#', data: { action: 'links#addLink' }

app/views/answers/_link_fields.html.slim
.nested-fields id="link_#{f.object.id || 'NEW_RECORD'}" data-controller="remove-link"
  p
    = f.label :name, 'Link name'
    = f.text_field :name

  p
    = f.label :url
    = f.text_field :url
    = f.hidden_field :_destroy, value: "false", data: { 'remove-link-target': 'destroyField' }

  = link_to 'Remove', '#', data: { action: 'remove-link#remove'}

app/views/answers/create.turbo_stream.slim
= turbo_stream.append 'answers' do
  = render partial: 'answers/answer', locals: { answer: @answer }

= render_flash_notice('Answer was successfully created.')

= turbo_stream.replace 'answer_form' do
  = render partial: 'answers/form', locals: { answer: @new_answer, question: @question }

app/views/answers/create_error.turbo_stream.slim
= turbo_stream.replace 'answer_form' do
  = render partial: 'answers/form', locals: { answer: @answer, question: @question }

app/views/answers/edit.html.slim
= turbo_frame_tag dom_id(@answer) do
  = render 'answers/form_edit', answer: @answer