config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  use_doorkeeper
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "questions#index"
  get 'search', to: 'search#index'

  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  namespace :api do
    namespace :v1 do
      use_doorkeeper

      resources :profiles, only: [:index] do
        get 'me', on: :collection
      end

      resources :questions, shallow: true, except: [:new, :edit] do
        resources :answers, shallow: true, only: [:index, :create, :update, :destroy] do
          resources :comments, shallow: true, only: [:index]
        end
        resources :comments, shallow: true, only: [:index]
      end
    end
  end

  resources :questions do
    member do
      patch :mark_best_answer
      patch :unmark_best_answer
    end

    resources :answers, shallow: true, except: [ :index, :show ] do
      resources :comments, shallow: true, only: [ :new, :create ]
      resource :subscriptions, only: [:create, :destroy], shallow: true

    end
    resource :subscriptions, only: [:create, :destroy], shallow: true

    resources :comments, shallow: true, only: [ :new, :create ]
  end
  resources :attachments, only: [ :destroy ]
  resources :links, only: [ :destroy ]
  resources :rewards, only: :index
  resources :votes, only: [ :create ] do
    collection do
      delete :destroy, to: 'votes#destroy', as: 'delete_vote'
    end
  end
  resources :live_feed, only: [ :index ]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Qna" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  <body>
  <!-- Navbar с использованием классов Bulma -->
  <nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="<%= questions_path %>">
      <span class="-img _glyph">
  <%= image_tag 'so-logo.png', alt: 'Stack Overflow Logo' %>
</span>
      </a>

    </div>

    <div class="navbar-menu">
      <div class="navbar-start">
        <% if user_signed_in? %>
          <div class="navbar-item">
            Logged in as <%= current_user.email %>
          </div>
          <a class="navbar-item" href="<%= rewards_path %>">
            Rewards
          </a>
          <a class="navbar-item" href="<%= oauth_applications_path %>">
            API keys
          </a>
          <a class="navbar-item" href="<%= destroy_user_session_path %>" data-turbo-method="delete">
            Sign out
          </a>
        <% else %>
          <a class="navbar-item" href="<%= new_user_session_path %>">
            Sign in
          </a>
        <% end %>
      </div>
    </div>
  </nav>

  <%= turbo_frame_tag 'flash-messages' do %>
    <%= render 'shared/flash' %>
  <% end %>
  <%= yield %>
  </body>
</html>